yubihsm.exceptions
==================

.. py:module:: yubihsm.exceptions

.. autoapi-nested-parse::

   Exceptions thrown by this library.



Exceptions
----------

.. autoapisummary::

   yubihsm.exceptions.YubiHsmError
   yubihsm.exceptions.YubiHsmConnectionError
   yubihsm.exceptions.YubiHsmDeviceError
   yubihsm.exceptions.YubiHsmInvalidRequestError
   yubihsm.exceptions.YubiHsmInvalidResponseError
   yubihsm.exceptions.YubiHsmAuthenticationError


Module Contents
---------------

.. py:exception:: YubiHsmError

   Bases: :py:obj:`Exception`


   Baseclass for YubiHSM errors.


.. py:exception:: YubiHsmConnectionError

   Bases: :py:obj:`YubiHsmError`


   The connection to the YubiHSM failed.


.. py:exception:: YubiHsmDeviceError(code)

   Bases: :py:obj:`YubiHsmError`


   The YubiHSM returned an error code.

   :param int code: The device error code.


   .. py:attribute:: code


.. py:exception:: YubiHsmInvalidRequestError

   Bases: :py:obj:`YubiHsmError`


   The request was not able to be sent to the YubiHSM.


.. py:exception:: YubiHsmInvalidResponseError

   Bases: :py:obj:`YubiHsmError`


   The YubiHSM returned an unexpected response.


.. py:exception:: YubiHsmAuthenticationError

   Bases: :py:obj:`YubiHsmError`


   Authentication failed.


